from Person import Person
from Job import Job
from Driver import Driver

#dummy data kelas Person
print("====================")
print("Person")
person1 = Person()
person1.setNIK("2022001")
person1.setName("Albert")
person1.setGender("Male")
person1.printPerson()
person1.sleep()

print("")
person2 = Person()
person2.setNIK("2022002")
person2.setName("Sarah")
person2.setGender("Female")
person2.printPerson()
person2.sleep()

print("")
person3 = Person()
person3.setNIK("2022003")
person3.setName("Jon")
person3.setGender("Male")
person3.printPerson()
person3.sleep()

print("")
person5 = Person()
person5.setNIK("2022004")
person5.setName("Snow")
person5.setGender("Male")
person5.printPerson()
person5.sleep()

print("")
person4 = Person()
person4.setNIK("2022005")
person4.setName("Kate")
person4.setGender("Female")
person4.printPerson()
person4.sleep()

#dummy data kelas Job
print("====================")
print("Job")
job1 = Job()
job1.setNIP("1111")
job1.setCompanyName("Deck Nine")
job1.setPosition("Game Director")
job1.printJob()

print("")
job2 = Job()
job2.setNIP("1112")
job2.setCompanyName("CD Projekt Red")
job2.setPosition("Senior Artist")
job2.printJob()

print("")
job3 = Job()
job3.setNIP("1113")
job3.setCompanyName("Indofood")
job3.setPosition("Quality Control")
job3.printJob()

print("")
job4 = Job()
job4.setNIP("1114")
job4.setCompanyName("Sinarmas")
job4.setPosition("Manajer")
job4.printJob()

print("")
job5 = Job()
job5.setNIP("1115")
job5.setCompanyName("Honda")
job5.setPosition("Mechanic")
job5.printJob()

#dummy data kelas Driver
print("====================")
print("Driver")
driver1 = Driver()
driver1.setNIK("2022011")
driver1.setName("Bruce")
driver1.setGender("Male")
driver1.setNIP("1121")
driver1.setCompanyName("Gojek")
driver1.setPosition("Driver")
driver1.setLicenseID("0001")
driver1.setActiveUntil("25/12/2027")
driver1.setVehicleType("Motorcycles")
driver1.printDriver()
driver1.sleep()

print("")
driver2 = Driver()
driver2.setNIK("2022012")
driver2.setName("Wayne")
driver2.setGender("Male")
driver2.setNIP("1122")
driver2.setCompanyName("Grab")
driver2.setPosition("Driver")
driver2.setLicenseID("0002")
driver2.setActiveUntil("10/04/2023")
driver2.setVehicleType("Cars")
driver2.printDriver()
driver2.sleep()

print("")
driver3 = Driver()
driver3.setNIK("2022013")
driver3.setName("Rolo")
driver3.setGender("Male")
driver3.setNIP("1123")
driver3.setCompanyName("FedEx")
driver3.setPosition("Driver")
driver3.setLicenseID("0003")
driver3.setActiveUntil("14/02/2024")
driver3.setVehicleType("Truck")
driver3.printDriver()
driver3.sleep()

print("")
driver4 = Driver()
driver4.setNIK("2022014")
driver4.setName("Olaf")
driver4.setGender("Male")
driver4.setNIP("1124")
driver4.setCompanyName("Evergreen")
driver4.setPosition("Trucker")
driver4.setLicenseID("0004")
driver4.setActiveUntil("01/01/2023")
driver4.setVehicleType("Truck")
driver4.printDriver()
driver4.sleep()

print("")
driver5 = Driver()
driver5.setNIK("2022015")
driver5.setName("Capone")
driver5.setGender("Male")
driver5.setNIP("1125")
driver5.setCompanyName("Uber")
driver5.setPosition("Driver")
driver5.setLicenseID("0005")
driver5.setActiveUntil("31/12/2023")
driver5.setVehicleType("Cars")
driver5.printDriver()
driver5.sleep()