from Vehicle import Vehicle
from Ship import Ship
from Airplane import Airplane

#dummy data kelas Vehicle
print("====================")
print("Vehicle")
vehicle1 = Vehicle()
vehicle1.setName("Cooper")
vehicle1.setFuelType("Petrol")
vehicle1.setMaxPassengers(5)
vehicle1.printVehicle()
vehicle1.Move()

vehicle2 = Vehicle()
vehicle2.setName("Puma")
vehicle2.setFuelType("Petrol")
vehicle2.setMaxPassengers(4)
print("")
vehicle2.printVehicle()
vehicle2.Move()

vehicle3 = Vehicle()
vehicle3.setName("Raptor")
vehicle3.setFuelType("Diesel")
vehicle3.setMaxPassengers(3)
print("")
vehicle3.printVehicle()
vehicle3.Move()

vehicle4 = Vehicle()
vehicle4.setName("Africa Twin")
vehicle4.setFuelType("Petrol")
vehicle4.setMaxPassengers(2)
print("")
vehicle4.printVehicle()
vehicle4.Move()

vehicle5 = Vehicle()
vehicle5.setName("Tenere")
vehicle5.setFuelType("Petrol")
vehicle5.setMaxPassengers(2)
print("")
vehicle5.printVehicle()
vehicle5.Move()
print("====================")

#dummy data kelas Ship
print("Ship")
ship1 = Ship()
ship1.setName("Arjuna")
ship1.setFuelType("Diesel")
ship1.setMaxPassengers(250)
ship1.setAge(10)
ship1.setShipType("Ferry")
ship1.setCountryOfManufacturer("Indonesia")
ship1.printShip()
ship1.Move()

ship2 = Ship()
ship2.setName("HMS Queen Elizabeth")
ship2.setFuelType("Diesel")
ship2.setMaxPassengers(500)
ship2.setAge(30)
ship2.setShipType("Aircraft Carrier")
ship2.setCountryOfManufacturer("UK")
print("")
ship2.printShip()
ship2.Move()

ship3 = Ship()
ship3.setName("USS Gerald R. Ford")
ship3.setFuelType("Nuclear")
ship3.setMaxPassengers(600)
ship3.setAge(15)
ship3.setShipType("Aircraft Carrier")
ship3.setCountryOfManufacturer("USA")
print("")
ship3.printShip()
ship3.Move()

ship4 = Ship()
ship4.setName("Evergreen")
ship4.setFuelType("Diesel")
ship4.setMaxPassengers(50)
ship4.setAge(10)
ship4.setShipType("Container Ship")
ship4.setCountryOfManufacturer("USA")
print("")
ship4.printShip()
ship4.Move()

ship5 = Ship()
ship5.setName("Yudistira")
ship5.setFuelType("Diesel")
ship5.setMaxPassengers(60)
ship5.setAge(10)
ship5.setShipType("Submarine")
ship5.setCountryOfManufacturer("Indonesia")
print("")
ship5.printShip()
ship5.Move()
print("====================")

#dummy data kelas Airplane
print("Airplane")
airplane1 = Airplane()
airplane1.setName("Boeing 747")
airplane1.setFuelType("Avtur")
airplane1.setMaxPassengers(400)
airplane1.setAge(20)
airplane1.setAirplaneType("Commuter Liners")
airplane1.setWingsLength(59.6)
airplane1.printAirplane()
airplane1.Move()

airplane2 = Airplane()
airplane2.setName("Airbus A220")
airplane2.setFuelType("Avtur")
airplane2.setMaxPassengers(160)
airplane2.setAge(10)
airplane2.setAirplaneType("Commuter Liners")
airplane2.setWingsLength(35.1)
print("")
airplane2.printAirplane()
airplane2.Move()

airplane3 = Airplane()
airplane3.setName("Cessna 172 Skyhawk")
airplane3.setFuelType("Avtur")
airplane3.setMaxPassengers(4)
airplane3.setAge(50)
airplane3.setAirplaneType("Turboprop")
airplane3.setWingsLength(11)
print("")
airplane3.printAirplane()
airplane3.Move()

airplane4 = Airplane()
airplane4.setName("Airbus A400M")
airplane4.setFuelType("Avtur")
airplane4.setMaxPassengers(4)
airplane4.setAge(20)
airplane4.setAirplaneType("Cargo Aircraft")
airplane4.setWingsLength(42.4)
print("")
airplane4.printAirplane()
airplane4.Move()

airplane5 = Airplane()
airplane5.setName("Embraer EMB 314 Super Tucano")
airplane5.setFuelType("Avtur")
airplane5.setMaxPassengers(2)
airplane5.setAge(23)
airplane5.setAirplaneType("Figther")
airplane5.setWingsLength(19.4)
print("")
airplane5.printAirplane()
airplane5.Move()
print("====================")